#!/usr/bin/env python

import sys,os, subprocess
from pathlib import Path

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"src")))

from code_generator import Generator
from semantic_analyzer import Analyzer
from parser import Parser
try:
	klein_file = sys.argv[1]
	
except:
	print("Klein Error: Invalid Input. Make sure you input either a .kln file or a directory of .kln files.")
else:
	if os.path.isdir(klein_file):
		for f in os.listdir(klein_file):
			filename = f.split("/")[-1]
			base_filename, extension = os.path.splitext(filename)
			if extension == ".kln" or extension == "":
				print("\nFILENAME:",filename)
				try:
					"WRITE LATER"
				except:
					print("Klein Warning: This file is either not a Klein program, or it doesn't exist. Skipping code generation...")
			else:
				continue
	else:
		filename = klein_file.split('/')[-1]
		base_filename, extension = os.path.splitext(filename)
		print('\nFILENAME:', filename)
		if extension == ".kln" or extension == "":
			try:
				content = open(klein_file).read()
				tree = Parser(content).parse()
				table = Analyzer(tree).analyze()
				imem = Generator(tree,table).generate()
				program_counter = 0
				tm_instructions = []
				for (instruction, description) in imem:
					if description == "#":
						print(instruction)
						continue
					else:
						print(program_counter, ":", instruction, description)
						tm_instructions.append(instruction)
						program_counter += 1
				tm_name = base_filename + ".tm"
				root = Path(__file__).resolve().parent
				output_dir = root / "programs" / "tm-programs"
				with open(os.path.join(output_dir,tm_name),'w') as f:
					for i, inst in enumerate(tm_instructions):
						f.write(f"{i} : {inst}\n")

			except:
				print("Klein Warning: This file is either not a Klein program, or it doesn't exist. Skipping code generation...")
		else:
			print("Klein Warning: This file is either not a Klein program, or it doesn't exist. Skipping code generation...") 

