#!/usr/bin/env python

import sys,os, subprocess
from pathlib import Path

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"src")))

from validate_semanticparser import validate

klein_file = sys.argv[1]
content = open(klein_file).read()
filename = klein_file.split('/')[-1].split('.')[0] + "_AST"
validate(content,filename=filename)
root = Path(__file__).resolve().parent
output_dir = root / "doc" / "GraphOutputs"
dot_path = output_dir / f"{filename}.dot"
png_path = output_dir / f"{filename}.png"
subprocess.run(['dot', '-Tpng', dot_path, '-o', png_path])