#!/usr/bin/env python

import sys,os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"src")))

from token_lister import list_tokens

klein_file = sys.argv[1]
if os.path.isdir(klein_file):
	for f in os.listdir(klein_file):
		filename = f.split("/")[-1]
		if os.path.splitext(filename)[-1] == ".kln":
			print("\nFILENAME:",filename)
			content = open(os.path.join(klein_file,f)).read()
			print(list_tokens(content))
		else:
			continue
else:
	content = open(klein_file).read()
	print(list_tokens(content))
