#!/usr/bin/env python

import sys,os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"..","src")))

from token_lister import list_tokens

klein_file = open(sys.argv[1])
content = klein_file.read()

print(list_tokens(content))
