#!/usr/bin/env python

import sys,os, subprocess
from pathlib import Path

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"src")))

from code_generator import Generator
from semantic_analyzer import Analyzer
from parser import Parser
try:
	klein_file = sys.argv[1]
except:
	print("Klein Error: Invalid Input. Make sure you input either a .kln file or a directory of .kln files.")
else:
	if os.path.isdir(klein_file):
		for f in os.listdir(klein_file):
			filename = f.split("/")[-1]
			base_filename, extension = os.path.splitext(filename)
			if extension == ".kln":
				print("\nFILENAME:",filename)
				content = open(os.path.join(klein_file,f)).read()
				tree = Parser(content).parse()
				table = Analyzer(tree)
				Generator(tree,table).generate()
			else:
				continue
	else:
		content = open(klein_file).read()
		tree = Parser(content).parse()
		table = Analyzer(tree)
		Generator(tree,table).generate()
