#!/usr/bin/env python

import sys,os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"..","src")))

from parse_validator import validate

klein_file = open(sys.argv[1])
content = klein_file.read()

validate(content)
