#!/usr/bin/env python

import sys,os, subprocess

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"src")))

from validate_semanticparser import validate

klein_file = open(sys.argv[1])
content = klein_file.read()

validate(content)

subprocess.run(['dot', '-Tpng', 'ast_output.dot', '-o', 'ast_output.png'])
