#!/usr/bin/env python

import sys,os, subprocess
from pathlib import Path

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__),"src")))

from validate_semanticparser import validate

try:
	klein_file = sys.argv[1]
except:
	print("Klein Error: Invalid Input. Make sure you input either a .kln file or a directory of .kln files.")
else:
	root = Path(__file__).resolve().parent
	output_dir = root / "doc" / "GraphOutputs"

	if os.path.isdir(klein_file):
		for f in os.listdir(klein_file):
			filename = f.split("/")[-1]
			base_filename, extension = os.path.splitext(filename)
			if extension == ".kln":
				print("\nFILENAME:",filename)
				output_name = base_filename + "_AST"
				content = open(os.path.join(klein_file,f)).read()
				validate(content,filename=output_name)
				subprocess.run(['dot', '-Tpng', output_dir / f"{output_name}.dot", '-o', output_dir / f"{output_name}.png"])
				
			else:
				continue
	else:
		content = open(klein_file).read()
		output_name = klein_file.split('/')[-1].split('.')[0] + "_AST"
		validate(content,filename=output_name)
		subprocess.run(['dot', '-Tpng', output_dir / f"{output_name}.dot", '-o', output_dir / f"{output_name}.png"])